# Задания для подготовки к семинару по numpy и matplotlib

In [7]:
# Запустите эту ячейку, чтобы подготовить блокнот к работе
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Задание 1

```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

Сколько способов создания такого массива `numpy` вы сможете придумать? Попробуйте не менее трех.

In [12]:
# Ваш код здесь

## Задание 2

Дан массив `grades`, содержащий баллы слушателей курса по английскому языку за экзамен. Строки массива соответствуют группам, а столбцы - участникам.

In [10]:
grades = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

### 2.1 Сколько всего слушателей сдавали экзамен?

Определите число элементов массива.

In [11]:
# Ваш код здесь

### 2.2 Сколько было групп и участников?

Определите форму массива - число строк и столбцов

In [14]:
# Ваш код здесь

### 2.3 Срезы данных

С помощью срезов получите:

 - Оценки первых трех групп
 - Оценки последних по счету участников каждой группы
 - Оценки участников с четным номером групп с четным номером

In [15]:
# Ваш код здесь

### 2.4 Сколько слушателей провалили экзамен?

Посчитайте, сколько слушателей провалили экзамен (получили оценку 0)?

In [16]:
# Ваш код здесь

### 2.5 Сколько слушателей набрали более 50 баллов?

Посчитайте, сколько слушателей получили свыше 50 баллов. Посчитайте, какая это доля слушателей.

In [ ]:
# Ваш код здесь

### 2.6 Сколько слушателей набрали от 50 до 70 баллов?

Посчитайте, сколько слушателей получили свыше 50, но не выше 70 баллов. Посчитайте, какая это доля слушателей.

In [21]:
# Ваш код здесь

### 2.7 Средние баллы

Рассчитайте средний балл среди всех участников, затем рассчитайте средний балл в каждой группе. Определите с помощью `numpy` номер группы, в которой средний балл был наивысшим (Python нумерует элементы массивов от нуля, а нумерация групп начинается с 1).

In [22]:
# Ваш код здесь

### 2.8 Продвинутый уровень языка

Рассчитайте, сколько в каждой группе слушателей с продвинутым уровнем знания языка - балл за экзамен выше 80. Какая это доля от числа участников группы?

In [23]:
# Ваш код здесь

### 2.9 Средний балл среди успешно сдавших экзамен


Отберите в массив `passed` только успешные результаты сдачи экзамена (балл не менее 40). 
Посчитайте средний балл по этим результатам.


In [24]:
# Ваш код здесь

### 2.10 Доля уcпешно сдавших экзамен

Какую форму имеет массив `passed`? Используя информацию о форме массивов `grades` и `passed`, посчитайте, какая доля слушателей успешно сдала экзамен.

In [25]:
# Ваш код здесь

### 2.11 Распределение баллов

Постройте гистограмму распределения баллов на экзамене. Воспроизведите вид графика, показанный на рисунке.
![](pics/exam_grades.png)

In [67]:
# Ваш код здесь

## Задание 3

Постройте на интервале $[\pi, \pi]$ графики двух функций: $y = \sin x$ и $y = 0.2 \cdot (x + 1) ^2 - 1$}

Воспроизведите вид графика, показанный на рисунке:
![](pics/functions.png)

In [66]:
# Ваш код здесь